=== digital-preservation/droid/droid-report/src/test/resources/droidDbUnit.dtd
<!--

    Copyright (c) 2016, The National Archives <pronom@nationalarchives.gov.uk>
    All rights reserved.

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following
    conditions are met:

     * Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.

     * Redistributions in binary form must reproduce the above copyright
       notice, this list of conditions and the following disclaimer in the
       documentation and/or other materials provided with the distribution.

     * Neither the name of the The National Archives nor the
       names of its contributors may be used to endorse or promote products
       derived from this software without specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
    AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
    IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
    PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
    CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
    EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
    PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
    PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
    LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
    NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
    SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

-->
<!ELEMENT dataset (
    FORMAT*,
    HIBERNATE_UNIQUE_KEY*,
    IDENTIFICATION*,
    IDENTIFICATIONMETHODS*,
    NODESTATUS*,
    PROFILE_RESOURCE_NODE*,
    RESOURCETYPE*)>

<!ELEMENT FORMAT EMPTY>
<!ATTLIST FORMAT
    PUID CDATA #REQUIRED
    EXT_ID CDATA #IMPLIED
    MIME_TYPE CDATA #IMPLIED
    NAME CDATA #IMPLIED
    VERSION CDATA #IMPLIED
>

<!ELEMENT HIBERNATE_UNIQUE_KEY EMPTY>
<!ATTLIST HIBERNATE_UNIQUE_KEY
    NEXT_HI CDATA #IMPLIED
>

<!ELEMENT IDENTIFICATION EMPTY>
<!ATTLIST IDENTIFICATION
    IDENTIFICATION_ID CDATA #REQUIRED
    FORMAT_ID CDATA #REQUIRED
    JOB_ID CDATA #REQUIRED
>

<!ELEMENT IDENTIFICATIONMETHODS EMPTY>
<!ATTLIST IDENTIFICATIONMETHODS
    IDENTIFICATION_METHOD_ID CDATA #REQUIRED
    IDENTIFICATION_METHOD CDATA #IMPLIED
    IDENTIFICATION_METHOD_DESCRIPTION CDATA #IMPLIED
>

<!ELEMENT NODESTATUS EMPTY>
<!ATTLIST NODESTATUS
    NODE_STATUS_ID CDATA #REQUIRED
    NODE_STATUS CDATA #IMPLIED
    NODE_STATUS_DESCRIPTION CDATA #IMPLIED
>

<!ELEMENT PROFILE_RESOURCE_NODE EMPTY>
<!ATTLIST PROFILE_RESOURCE_NODE
    NODE_ID CDATA #REQUIRED
    ERROR_MESSAGE CDATA #IMPLIED
    EXTENSION CDATA #IMPLIED
    IDENTIFICATION_METHOD CDATA #IMPLIED
    LAST_MODIFIED_DATE CDATA #IMPLIED
    NAME CDATA #REQUIRED
    NODE_STATUS CDATA #IMPLIED
    RESOURCE_TYPE CDATA #REQUIRED
    FILE_SIZE CDATA #IMPLIED
    PREFIX CDATA #IMPLIED
    PREFIX_PLUS_ONE CDATA #IMPLIED
    URI CDATA #REQUIRED
    PARENT_ID CDATA #IMPLIED
>

<!ELEMENT RESOURCETYPE EMPTY>
<!ATTLIST RESOURCETYPE
    RESOURCE_TYPE_ID CDATA #REQUIRED
    RESOURCE_TYPE CDATA #IMPLIED
    RESOURCE_TYPE_DESCRIPTION CDATA #IMPLIED
>

=== digital-preservation/droid/droid-report/src/test/resources/report-test-data.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2012, The National Archives <pronom@nationalarchives.gsi.gov.uk>
    All rights reserved.

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following
    conditions are met:

     * Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.

     * Redistributions in binary form must reproduce the above copyright
       notice, this list of conditions and the following disclaimer in the
       documentation and/or other materials provided with the distribution.

     * Neither the name of the The National Archives nor the
       names of its contributors may be used to endorse or promote products
       derived from this software without specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
    AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
    IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
    PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
    CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
    EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
    PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
    PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
    LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
    NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
    SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

-->
<!DOCTYPE dataset SYSTEM "droidDbUnit.dtd">

<dataset> 
<FORMAT   PUID="NULL"                                                                                                                                                         				/>
<FORMAT   PUID="fmt/126"                 EXT_ID="135"                    MIME_TYPE="application/vnd.ms-powerpoint"       NAME="Microsoft Powerpoint Presentation"             VERSION="97-2002"		/>
<FORMAT   PUID="x-fmt/111"               EXT_ID="163"                    MIME_TYPE="text/plain"                          NAME="Plain Text File"                               				/>
<FORMAT   PUID="fmt/101"                 EXT_ID="638"                    MIME_TYPE="text/xml"                            NAME="Extensible Markup Language"                    VERSION="1.0"		/>
<FORMAT   PUID="fmt/40"                  EXT_ID="690"                    MIME_TYPE="application/msword"                  NAME="Microsoft Word for Windows Document"           VERSION="97-2003"		/>
<FORMAT   PUID="fmt/111"                 EXT_ID="767"                                                                    NAME="OLE2 Compound Document Format"                 				/>
<FORMAT   PUID="x-fmt/411"               EXT_ID="776"                    MIME_TYPE="application/octet-stream"            NAME="Windows Portable Executable"                   				/>
   
<PROFILE_RESOURCE_NODE   NODE_ID="1"                                                                                      			                                                                                        IDENTIFICATION_METHOD="2"                                     LAST_MODIFIED_DATE="2010-05-13 15:57:00"                                     NAME="C:\My Folder"                                     NODE_STATUS="1"                                     RESOURCE_TYPE="1"                                                                      URI="file:/C:/My%20Folder/"                                                                                          />    
<PROFILE_RESOURCE_NODE   NODE_ID="2"                                                                                      			                                                                                          IDENTIFICATION_METHOD="2"                                     LAST_MODIFIED_DATE="2010-02-18 12:24:26"                                    NAME ="documents"                                        NODE_STATUS="1"                                     RESOURCE_TYPE="1"                                                                     URI="file:/C:/My%20Folder/documents/"                                                               PARENT_ID="1"    />    
<PROFILE_RESOURCE_NODE   NODE_ID="3"              ERROR_MESSAGE="C:\My Folder\documents\UserTask.doc (Access is denied)"                                                    EXTENSION="doc"                                                                                                   LAST_MODIFIED_DATE="2009-12-03 17:26:17"                                     NAME="UserTask.doc"                                     NODE_STATUS="4"                                     RESOURCE_TYPE="0"                                     FILE_SIZE="40960"                URI="file:/C:/My%20Folder/documents/UserTask.doc"                                                   PARENT_ID="2"    />    
<PROFILE_RESOURCE_NODE   NODE_ID="4"                                                                                      			                                                                                         IDENTIFICATION_METHOD="2"                                     LAST_MODIFIED_DATE="2010-02-18 12:34:06"                                     NAME="ExcelSheets"                                      NODE_STATUS="1"                                     RESOURCE_TYPE="1"                                                                      URI="file:/C:/My%20Folder/ExcelSheets/"                                                             PARENT_ID="1"    />    
<PROFILE_RESOURCE_NODE   NODE_ID="5"                                                                                      			                                                                                        IDENTIFICATION_METHOD="2"                                     LAST_MODIFIED_DATE="2010-02-18 12:34:08"                                     NAME="textfiles"                                        NODE_STATUS="1"                                     RESOURCE_TYPE="1"                                                                       URI="file:/C:/My%20Folder/ExcelSheets/textfiles/"                                                   PARENT_ID="4"    />    
<PROFILE_RESOURCE_NODE   NODE_ID="7"                                                                                      			                                    EXTENSION="txt"                                     IDENTIFICATION_METHOD="1"                                     LAST_MODIFIED_DATE="2009-08-06 16:11:26"                                     NAME="LICENSE.txt"                                      NODE_STATUS="1"                                     RESOURCE_TYPE="0"                                     FILE_SIZE="12933"                URI="file:/C:/My%20Folder/ExcelSheets/textfiles/LICENSE.txt"                                        PARENT_ID="5"    />    
<PROFILE_RESOURCE_NODE   NODE_ID="6"                                                                                      			                                     EXTENSION="doc"                                     IDENTIFICATION_METHOD="0"                                     LAST_MODIFIED_DATE="2009-11-02 09:10:18"                                     NAME="Change Date Format in Mailmerge.doc"              NODE_STATUS="1"                                     RESOURCE_TYPE="0"                                     FILE_SIZE="256000"               URI="file:/C:/My%20Folder/documents/Change%20Date%20Format%20in%20Mailmerge.doc"                    PARENT_ID="2"    />    
<PROFILE_RESOURCE_NODE   NODE_ID="8"                                                                                      			                                    EXTENSION="txt"                                     IDENTIFICATION_METHOD="1"                                     LAST_MODIFIED_DATE="2008-01-29 17:50:11"                                     NAME="LEGALNOTICE.txt"                                  NODE_STATUS="1"                                     RESOURCE_TYPE="0"                                     FILE_SIZE="1845"                 URI="file:/C:/My%20Folder/ExcelSheets/textfiles/LEGALNOTICE.txt"                                    PARENT_ID="5"    />    
<PROFILE_RESOURCE_NODE   NODE_ID="9"                                                                                      			                                    EXTENSION="txt"                                     IDENTIFICATION_METHOD="1"                                     LAST_MODIFIED_DATE="2008-01-29 17:50:11"                                     NAME="DISTRIBUTION.txt"                                 NODE_STATUS="1"                                     RESOURCE_TYPE="0"                                     FILE_SIZE="1852"                 URI="file:/C:/My%20Folder/ExcelSheets/textfiles/DISTRIBUTION.txt"                                   PARENT_ID="5"    />    
<PROFILE_RESOURCE_NODE   NODE_ID="10"                                                                                     			                                    EXTENSION="txt"                                     IDENTIFICATION_METHOD="1"                                     LAST_MODIFIED_DATE="2004-12-13 10:41:42"                                     NAME="Artistic.txt"                                     NODE_STATUS="1"                                     RESOURCE_TYPE="0"                                     FILE_SIZE="6242"                 URI="file:/C:/My%20Folder/ExcelSheets/textfiles/Artistic.txt"                                       PARENT_ID="5"    />
