=== digital-preservation/droid/droid-report/src/main/resources/xsd/planets.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2016, The National Archives <pronom@nationalarchives.gov.uk>
    All rights reserved.

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following
    conditions are met:

     * Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.

     * Redistributions in binary form must reproduce the above copyright
       notice, this list of conditions and the following disclaimer in the
       documentation and/or other materials provided with the distribution.

     * Neither the name of the The National Archives nor the
       names of its contributors may be used to endorse or promote products
       derived from this software without specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
    AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
    IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
    PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
    CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
    EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
    PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
    PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
    LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
    NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
    SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:st="http://www.nationalarchives.gov.uk/CollectionProfile"
            targetNamespace="http://www.nationalarchives.gov.uk/CollectionProfile"
            elementFormDefault="qualified">
   <xsd:annotation>
       <xsd:documentation xml:lang="en">
           The DROID File Profiling Schema
       </xsd:documentation>
   </xsd:annotation>
   <xsd:element name="FileProfile" type="st:FileProfileType">   
   </xsd:element>
   <xsd:complexType name="PathsProcessedType">
       <xsd:choice minOccurs="0" maxOccurs="unbounded">
           <xsd:element name="pathItem" type="xsd:string"/>
       </xsd:choice>
   </xsd:complexType>  
   <xsd:complexType name="FileProfileType">
       <xsd:sequence>
           <xsd:element name="profilingStartDate" type="xsd:dateTime"  />
           <xsd:element name="profilingEndDate" type="xsd:dateTime" />
           <xsd:element name="profilingSaveDate" type="xsd:dateTime" />
           <xsd:element name="totalReadableFiles" type="xsd:integer" />
           <xsd:element name="totalUnreadableFiles" type="xsd:integer" />
           <xsd:element name="totalUnreadableFolders" type="xsd:integer" />
           <xsd:element name="totalSize" type="xsd:decimal" />
           <xsd:element name="smallestSize" type="xsd:decimal" />
           <xsd:element name="largestSize" type="xsd:decimal" />
           <xsd:element name="meanSize" type="xsd:decimal" />
           <xsd:element name="pathsProcessed" type="st:PathsProcessedType" />
           <xsd:element name="byYear" type="st:ByYearType" />
           <xsd:element name="byFormat" type="st:ByFormatType" />
       </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="ByFormatType">
       <xsd:choice minOccurs="0" maxOccurs="unbounded">
           <xsd:element name="formatItem" type="st:FormatItemType"/>
       </xsd:choice>
   </xsd:complexType>
   <xsd:complexType name="FormatItemType">
       <xsd:sequence>
           <xsd:element name="PUID" type="xsd:string"/>
           <xsd:element name="MIME" type="xsd:string"/>
           <xsd:element name="FormatName" type="xsd:string"/>
           <xsd:element name="FormatVersion" type="xsd:string"/>
           <xsd:element name="numFiles" type="xsd:integer"/>
           <xsd:element name="totalFileSize" type="xsd:decimal"/>
       </xsd:sequence>
   </xsd:complexType>
   <xsd:complexType name="ByYearType">
       <xsd:choice minOccurs="0" maxOccurs="unbounded">
           <xsd:element name="yearItem" type="st:YearItemType"/>
       </xsd:choice>
   </xsd:complexType>
   <xsd:complexType name="YearItemType">
       <xsd:sequence>
           <xsd:element name="year" type="xsd:gYear"/>
           <xsd:element name="numFiles" type="xsd:integer"/>
           <xsd:element name="totalFileSize" type="xsd:decimal"/>
       </xsd:sequence>
   </xsd:complexType>   
 </xsd:schema>

=== digital-preservation/droid/droid-report/src/main/resources/xsd/planets.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2016, The National Archives <pronom@nationalarchives.gov.uk>
    All rights reserved.

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following
    conditions are met:

     * Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.

     * Redistributions in binary form must reproduce the above copyright
       notice, this list of conditions and the following disclaimer in the
       documentation and/or other materials provided with the distribution.

     * Neither the name of the The National Archives nor the
       names of its contributors may be used to endorse or promote products
       derived from this software without specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
    AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
    IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
    PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
    CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
    EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
    PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
    PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
    LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
    NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
    SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

-->
<st:FileProfile xmlns:st="http://www.nationalarchives.gov.uk/CollectionProfile" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nationalarchives.gov.uk/CollectionProfile planets.xsd ">
  <st:profilingStartDate>2001-12-31T12:00:00</st:profilingStartDate>
  <st:profilingEndDate>2001-12-31T12:00:00</st:profilingEndDate>
  <st:profilingSaveDate>2001-12-31T12:00:00</st:profilingSaveDate>
  <st:totalReadableFiles>0</st:totalReadableFiles>
  <st:totalUnreadableFiles>0</st:totalUnreadableFiles>
  <st:totalUnreadableFolders>0</st:totalUnreadableFolders>
  <st:totalSize>0.0</st:totalSize>
  <st:smallestSize>0.0</st:smallestSize>
  <st:largestSize>0.0</st:largestSize>
  <st:meanSize>0.0</st:meanSize>
  <st:pathsProcessed>
    <st:pathItem>st:pathItem</st:pathItem>
  </st:pathsProcessed>
  <st:byYear>
    <st:yearItem>
      <st:year>2001</st:year>
      <st:numFiles>0</st:numFiles>
      <st:totalFileSize>0.0</st:totalFileSize>
    </st:yearItem>
  </st:byYear>
  <st:byFormat>
    <st:formatItem>
      <st:PUID>st:PUID</st:PUID>
      <st:MIME>st:MIME</st:MIME>
      <st:FormatName>st:FormatName</st:FormatName>
      <st:FormatVersion>st:FormatVersion</st:FormatVersion>
      <st:numFiles>0</st:numFiles>
      <st:totalFileSize>0.0</st:totalFileSize>
    </st:formatItem>
  </st:byFormat>
</st:FileProfile>
